import { StyleSheet } from "react-native";
import type { Colors } from "../../src/theme/colors";

export function makeStyles(c: Colors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: c.bg },

    navbar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: c.surface,
      borderBottomWidth: 1,
      borderColor: c.border,
    },
    navBtn: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 10,
    },
    navTitle: {
      fontSize: 16,
      fontWeight: "800",
      color: c.primaryText,
      flex: 1,
      textAlign: "center",
    },

    scroll: { paddingBottom: 40 },

    // Header card
    headerCard: {
      margin: 16,
      backgroundColor: c.surface,
      borderRadius: 20,
      padding: 24,
      alignItems: "center",
      borderWidth: 1,
      borderColor: c.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    avatarWrap: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: c.primaryLight,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
    },
    avatarText: { fontSize: 24, fontWeight: "900", color: c.primaryDark },
    name: {
      fontSize: 22,
      fontWeight: "900",
      color: c.primaryText,
      marginBottom: 8,
      textAlign: "center",
    },
    badgeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flexWrap: "wrap",
      justifyContent: "center",
      marginBottom: 8,
    },
    typeBadge: {
      paddingVertical: 4,
      paddingHorizontal: 12,
      borderRadius: 999,
    },
    typeBadgeText: { fontSize: 12, fontWeight: "700" },
    verifiedBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: c.primaryLight,
    },
    verifiedText: { fontSize: 12, fontWeight: "700", color: c.primary },
    memberSince: { fontSize: 12, color: c.mutedText, marginTop: 4 },

    // Sections
    section: {
      marginHorizontal: 16,
      marginBottom: 12,
      backgroundColor: c.surface,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: c.border,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 10,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: "800",
      color: c.primaryText,
      textTransform: "uppercase",
      letterSpacing: 0.3,
    },
    bioText: {
      fontSize: 15,
      color: c.secondaryText,
      lineHeight: 22,
    },
    infoText: {
      fontSize: 15,
      fontWeight: "700",
      color: c.primaryText,
      marginBottom: 2,
    },
    infoSubText: { fontSize: 13, color: c.secondaryText },

    // Skills
    skillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    skillChipWrap: { flexDirection: "column", alignItems: "flex-start", gap: 3 },
    skillChip: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 5,
      paddingHorizontal: 12,
      borderRadius: 999,
      backgroundColor: c.primaryLight,
      borderWidth: 1,
      borderColor: c.primary,
      gap: 5,
    },
    skillChipText: { fontSize: 12, fontWeight: "700", color: c.primaryDark },
    endorseBadge: {
      backgroundColor: c.primary,
      borderRadius: 99,
      minWidth: 18,
      height: 18,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 4,
    },
    endorseBadgeText: { fontSize: 10, fontWeight: "800", color: "#FFFFFF" },
    endorseBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      paddingVertical: 2,
      paddingHorizontal: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: c.primary,
      backgroundColor: c.primaryLight,
    },
    endorseBtnText: { fontSize: 10, fontWeight: "700", color: c.primary },
    endorsedByMeTag: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      paddingVertical: 2,
      paddingHorizontal: 6,
    },
    endorsedByMeText: { fontSize: 10, color: c.success, fontWeight: "600" },

    // LinkedIn button
    linkedinBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: c.infoLight,
      borderWidth: 1.5,
      borderColor: c.info,
      alignSelf: "flex-start",
    },
    linkedinBtnText: { fontSize: 14, fontWeight: "700", color: c.info },

    // Not found
    notFound: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
    },
    notFoundText: { fontSize: 16, color: c.mutedText },
    backBtn: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 12,
      backgroundColor: c.primary,
    },
    backBtnText: { color: "#FFFFFF", fontWeight: "700" },
  });
}
