import { StyleSheet } from "react-native";

export const theme = {
  primary: "#0D9488",
  bg: "#F8FAFC",
  surface: "#FFFFFF",
  primaryText: "#0F172A",
  secondaryText: "#64748B",
  border: "#E2E8F0",
  danger: "#DC2626",
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.bg },
  scroll: { flex: 1, padding: 24 },
  h1: {
    fontSize: 26,
    fontWeight: "900",
    color: theme.primaryText,
    marginTop: 24,
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 14,
    color: theme.secondaryText,
    marginBottom: 28,
    lineHeight: 20,
  },
  label: {
    fontSize: 13,
    fontWeight: "800",
    color: theme.primaryText,
    marginBottom: 6,
    marginTop: 16,
  },
  required: { color: theme.danger },
  input: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 12,
    padding: 13,
    fontSize: 15,
    color: theme.primaryText,
    backgroundColor: theme.surface,
  },
  errorMsg: {
    color: theme.danger,
    fontSize: 13,
    fontWeight: "600",
    marginTop: 14,
    textAlign: "center",
  },
  successMsg: {
    color: "#10B981",
    fontSize: 13,
    fontWeight: "600",
    marginTop: 14,
    textAlign: "center",
  },
  continueBtn: {
    marginTop: 28,
    height: 52,
    borderRadius: 14,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  continueBtnDisabled: { opacity: 0.6 },
  continueBtnText: { color: "#FFFFFF", fontWeight: "900", fontSize: 16 },
  footer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 4,
    marginTop: 20,
    marginBottom: 32,
  },
  footerText: { fontSize: 13, color: theme.secondaryText },
  footerLink: { fontSize: 13, fontWeight: "800", color: theme.primary },
});
