import { Dimensions, StyleSheet } from "react-native";
import type { Colors } from "../src/theme/colors";

const { width } = Dimensions.get("window");

export const SCENE_W = Math.min(340, width - 28);
export const SCENE_H = 330;

export function makeStyles(c: Colors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.bg,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 24,
      paddingTop: 8,
      paddingBottom: 4,
    },
    langToggle: {
      flexDirection: "row",
      backgroundColor: c.surfaceAlt,
      borderRadius: 10,
      padding: 3,
      gap: 2,
    },
    langBtn: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 7,
    },
    langBtnActive: {
      backgroundColor: c.primary,
    },
    langText: {
      fontSize: 13,
      fontWeight: "700",
      color: c.secondaryText,
    },
    langTextActive: {
      color: "#FFFFFF",
    },
    heroArea: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
    },
    heroHalo: {
      position: "absolute",
      width: 260,
      height: 260,
      borderRadius: 130,
      backgroundColor: c.primaryLight,
      top: 64,
    },
    sceneWrap: {
      width: SCENE_W,
      height: SCENE_H,
      alignItems: "center",
      justifyContent: "center",
    },
    sceneSvg: {
      position: "absolute",
      top: 0,
      left: 0,
    },
    badgeLeft: {
      position: "absolute",
      top: 86,
      left: 24,
      backgroundColor: c.surface,
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: c.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
      elevation: 6,
    },
    badgeRight: {
      position: "absolute",
      top: 124,
      right: 20,
      backgroundColor: c.surface,
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: c.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
      elevation: 6,
    },
    badgeBottom: {
      position: "absolute",
      bottom: 42,
      right: 62,
      backgroundColor: c.surface,
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: c.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.08,
      shadowRadius: 18,
      elevation: 6,
    },
    badgeText: {
      fontSize: 12,
      fontWeight: "800",
      color: c.primaryText,
    },
    backSheetLeft: {
      position: "absolute",
      width: 236,
      height: 164,
      borderRadius: 30,
      backgroundColor: "#7C3AED",
      opacity: 0.22,
      transform: [
        { translateX: -34 },
        { translateY: -12 },
        { rotateZ: "-18deg" },
      ],
    },
    backSheetRight: {
      position: "absolute",
      width: 232,
      height: 156,
      borderRadius: 30,
      backgroundColor: "#F97316",
      opacity: 0.18,
      transform: [{ translateX: 34 }, { translateY: 0 }, { rotateZ: "14deg" }],
    },
    studentCard: {
      width: 252,
      height: 212,
      borderRadius: 32,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
      padding: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.14,
      shadowRadius: 24,
      elevation: 16,
    },
    studentHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 14,
    },
    profilePill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: c.surfaceAlt,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    profileDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: c.primary,
    },
    profilePillText: {
      fontSize: 11,
      fontWeight: "800",
      color: c.primaryText,
    },
    statusPill: {
      backgroundColor: c.primaryLight,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    statusPillText: {
      fontSize: 11,
      fontWeight: "800",
      color: c.primaryDark,
    },
    avatarWrap: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
    },
    avatarHair: {
      position: "absolute",
      top: 28,
      width: 74,
      height: 46,
      borderRadius: 28,
      backgroundColor: "#0F172A",
    },
    avatarHead: {
      position: "absolute",
      top: 38,
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: "#F4C7A1",
      zIndex: 2,
    },
    avatarBody: {
      position: "absolute",
      top: 90,
      width: 116,
      height: 70,
      borderTopLeftRadius: 44,
      borderTopRightRadius: 44,
      borderBottomLeftRadius: 26,
      borderBottomRightRadius: 26,
      backgroundColor: c.primary,
    },
    laptopScreen: {
      position: "absolute",
      top: 118,
      width: 136,
      height: 72,
      borderRadius: 16,
      backgroundColor: "#1E293B",
      borderWidth: 6,
      borderColor: "#E2E8F0",
      zIndex: 3,
    },
    laptopBase: {
      position: "absolute",
      top: 184,
      width: 160,
      height: 14,
      borderRadius: 8,
      backgroundColor: "#CBD5E1",
      zIndex: 1,
    },
    metricRow: {
      flexDirection: "row",
      gap: 8,
      marginTop: 10,
    },
    metricCardPrimary: {
      flex: 1.2,
      backgroundColor: c.primaryLight,
      borderRadius: 16,
      paddingHorizontal: 10,
      paddingVertical: 9,
    },
    metricCardSecondary: {
      flex: 1,
      backgroundColor: c.surfaceAlt,
      borderRadius: 16,
      paddingHorizontal: 10,
      paddingVertical: 9,
    },
    metricLabel: {
      fontSize: 11,
      fontWeight: "700",
      color: c.primaryText,
      lineHeight: 14,
    },
    bottom: {
      paddingHorizontal: 28,
      paddingBottom: 32,
    },
    appName: {
      fontSize: 32,
      fontWeight: "900",
      color: c.primaryText,
      letterSpacing: -1,
      marginBottom: 6,
    },
    tagline: {
      fontSize: 20,
      fontWeight: "500",
      color: c.primaryText,
      lineHeight: 34,
      letterSpacing: -0.9,
      marginBottom: 10,
    },
    subtitle: {
      fontSize: 15,
      color: c.secondaryText,
      lineHeight: 22,
      marginBottom: 28,
    },
    createBtn: {
      height: 54,
      borderRadius: 16,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 14,
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 12,
      elevation: 6,
    },
    createBtnText: {
      color: "#FFFFFF",
      fontWeight: "900",
      fontSize: 16,
      letterSpacing: 0.2,
    },
    signInRow: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 4,
    },
    signInPrompt: {
      fontSize: 14,
      color: c.secondaryText,
    },
    signInLink: {
      fontSize: 14,
      fontWeight: "800",
      color: c.primary,
    },
  });
}
