import { StyleSheet } from "react-native";

export const theme = {
  primary: "#0D9488",
  primaryLight: "#CCFBF1",
  bg: "#F8FAFC",
  surface: "#FFFFFF",
  surfaceAlt: "#F1F5F9",
  primaryText: "#0F172A",
  secondaryText: "#64748B",
  mutedText: "#94A3B8",
  border: "#E2E8F0",
  success: "#10B981",
  successLight: "#ECFDF5",
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.bg },
  flex: { flex: 1 },

  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surface,
    gap: 8,
  },
  backBtn: { padding: 8 },
  headerInfo: { flex: 1 },
  headerName: { fontSize: 17, fontWeight: "800", color: theme.primaryText },
  headerSub: { fontSize: 12, color: theme.mutedText, fontWeight: "500" },
  completeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: theme.successLight,
    borderWidth: 1,
    borderColor: theme.success,
  },
  completeBtnText: { fontSize: 12, fontWeight: "700", color: theme.success },

  messageList: { padding: 16, gap: 8, flexGrow: 1 },

  msgWrap: { maxWidth: "80%", gap: 2 },
  msgWrapMe: { alignSelf: "flex-end", alignItems: "flex-end" },
  msgWrapOther: { alignSelf: "flex-start", alignItems: "flex-start" },

  bubble: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 18,
  },
  bubbleMe: {
    backgroundColor: theme.primary,
    borderBottomRightRadius: 4,
  },
  bubbleOther: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
    borderBottomLeftRadius: 4,
  },
  msgText: { fontSize: 14, lineHeight: 20 },
  msgTextMe: { color: "#FFFFFF" },
  msgTextOther: { color: theme.primaryText },
  msgTime: { fontSize: 10, color: theme.mutedText, marginHorizontal: 4 },
  msgMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 2,
  },
  readTick: { fontSize: 9, color: theme.mutedText, marginLeft: 4 },
  readTickSeen: { color: theme.primary },

  templateRow: {
    maxHeight: 42,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    backgroundColor: theme.surface,
  },
  templateRowContent: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  templateChip: {
    paddingVertical: 5,
    paddingHorizontal: 11,
    borderRadius: 14,
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.border,
  },
  templateChipText: {
    fontSize: 12,
    color: theme.primaryText,
    fontWeight: "600",
  },

  emptyWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingTop: 80,
  },
  emptyText: { fontSize: 14, color: theme.mutedText },

  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surface,
  },
  input: {
    flex: 1,
    minHeight: 42,
    maxHeight: 120,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 21,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 14,
    color: theme.primaryText,
  },
  sendBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  sendBtnDisabled: { opacity: 0.4 },
});
