import { StyleSheet } from "react-native";
import type { Colors } from "../../../src/theme/colors";

export function makeStyles(c: Colors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: c.bg },
    flex: { flex: 1 },

    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingTop: 8,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
      gap: 8,
    },
    backBtn: { padding: 8 },
    headerInfo: { flex: 1 },
    headerName: { fontSize: 17, fontWeight: "800", color: c.primaryText },
    headerSub: { fontSize: 12, color: c.mutedText, fontWeight: "500" },
    completeBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 10,
      backgroundColor: c.successLight,
      borderWidth: 1,
      borderColor: c.success,
    },
    completeBtnText: { fontSize: 12, fontWeight: "700", color: c.success },
    headerActions: { flexDirection: "row", alignItems: "center", gap: 6 },
    headerIconBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.surfaceAlt,
      borderWidth: 1,
      borderColor: c.border,
    },
    headerCallBtn: {
      backgroundColor: c.success,
      borderColor: c.success,
    },

    messageList: { padding: 16, gap: 8, flexGrow: 1 },

    msgWrap: { maxWidth: "80%", gap: 2 },
    msgWrapMe: { alignSelf: "flex-end", alignItems: "flex-end" },
    msgWrapOther: { alignSelf: "flex-start", alignItems: "flex-start" },

    bubble: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 18,
    },
    bubbleMe: {
      backgroundColor: c.primary,
      borderBottomRightRadius: 4,
    },
    bubbleOther: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
      borderBottomLeftRadius: 4,
    },
    msgText: { fontSize: 14, lineHeight: 20 },
    msgTextMe: { color: "#FFFFFF" },
    msgTextOther: { color: c.primaryText },
    msgTime: { fontSize: 10, color: c.mutedText, marginHorizontal: 4 },
    msgMeta: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 2,
    },
    readTick: { fontSize: 9, color: c.mutedText, marginLeft: 4 },
    readTickSeen: { color: c.primary },

    templateRow: {
      maxHeight: 42,
      borderTopWidth: 1,
      borderTopColor: c.border,
      backgroundColor: c.surface,
    },
    templateRowContent: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      gap: 6,
      flexDirection: "row",
      alignItems: "center",
    },
    templateChip: {
      paddingVertical: 5,
      paddingHorizontal: 11,
      borderRadius: 14,
      backgroundColor: c.surfaceAlt,
      borderWidth: 1,
      borderColor: c.border,
    },
    templateChipText: {
      fontSize: 12,
      color: c.primaryText,
      fontWeight: "600",
    },

    emptyWrap: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      paddingTop: 80,
    },
    emptyText: { fontSize: 14, color: c.mutedText },

    // Context card (listing banner — like Vinted/OLX)
    contextCard: {
      marginHorizontal: 12,
      marginTop: 12,
      marginBottom: 4,
      backgroundColor: c.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.border,
      overflow: "hidden",
    },
    contextCardBody: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      gap: 10,
    },
    contextCardIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: c.primaryLight,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    contextCardInfo: { flex: 1, gap: 3 },
    contextCardTitle: {
      fontSize: 14,
      fontWeight: "800",
      color: c.primaryText,
      lineHeight: 19,
    },
    contextCardChips: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 5,
      marginTop: 2,
    },
    contextChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: 8,
      backgroundColor: c.surfaceAlt,
    },
    contextChipGreen: { backgroundColor: c.successLight },
    contextChipText: {
      fontSize: 11,
      fontWeight: "700",
      color: c.secondaryText,
    },
    contextChipTextGreen: { color: c.success },
    contextCardViewBtn: {
      borderTopWidth: 1,
      borderTopColor: c.border,
      paddingVertical: 9,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
    },
    contextCardViewBtnText: {
      fontSize: 13,
      fontWeight: "700",
      color: c.primary,
    },

    inputRow: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: 8,
      paddingHorizontal: 12,
      paddingTop: 8,
      paddingBottom: 10,
      borderTopWidth: 1,
      borderColor: c.border,
    },
    input: {
      flex: 1,
      minHeight: 42,
      maxHeight: 120,
      backgroundColor: c.surfaceAlt,
      borderRadius: 21,
      paddingHorizontal: 16,
      paddingVertical: 10,
      fontSize: 14,
      color: c.primaryText,
    },
    sendBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    sendBtnDisabled: { opacity: 0.4 },
  });
}
