import { StyleSheet } from "react-native";

export const theme = {
  primary: "#0D9488",
  primaryLight: "#CCFBF1",
  primaryDark: "#0F766E",
  bg: "#F8FAFC",
  surface: "#FFFFFF",
  surfaceAlt: "#F1F5F9",
  primaryText: "#0F172A",
  secondaryText: "#64748B",
  mutedText: "#94A3B8",
  border: "#E2E8F0",
  success: "#10B981",
  successLight: "#D1FAE5",
  warning: "#F59E0B",
  warningLight: "#FEF3C7",
  error: "#EF4444",
  errorLight: "#FEE2E2",
  employer: "#7C3AED",
  employerLight: "#EDE9FE",
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.bg },

  navbar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surface,
    gap: 4,
  },
  navBtn: { padding: 10, borderRadius: 10 },
  navRight: { flexDirection: "row", alignItems: "center" },
  navTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
    color: theme.primaryText,
  },

  scroll: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 16 },

  heroCard: {
    backgroundColor: theme.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 18,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },

  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 12,
  },
  roleBadge: { paddingVertical: 4, paddingHorizontal: 10, borderRadius: 8 },
  roleBadgeText: { fontSize: 12, fontWeight: "700" },
  catBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: theme.surfaceAlt,
  },
  catBadgeText: { fontSize: 12, fontWeight: "600", color: theme.secondaryText },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusText: { fontSize: 12, fontWeight: "700" },

  heroTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: theme.primaryText,
    lineHeight: 30,
    marginBottom: 14,
    letterSpacing: -0.3,
  },

  metaRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 },
  metaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 11,
    borderRadius: 10,
    backgroundColor: theme.surfaceAlt,
  },
  metaText: { fontSize: 13, color: theme.secondaryText, fontWeight: "600" },
  wageChip: { backgroundColor: "#ECFDF5" },
  wageText: { color: "#065F46", fontWeight: "700" },

  posterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingTop: 14,
    borderTopWidth: 1,
    borderColor: theme.border,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.primaryLight,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { fontSize: 14, fontWeight: "800", color: theme.primaryDark },
  posterName: { fontSize: 14, fontWeight: "800", color: theme.primaryText },
  posterLabel: { fontSize: 12, color: theme.mutedText },

  section: {
    backgroundColor: theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 16,
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: theme.primaryText,
    flex: 1,
  },
  descText: { fontSize: 14, color: theme.secondaryText, lineHeight: 22 },

  appliedBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 14,
    borderRadius: 14,
    marginBottom: 12,
    backgroundColor: theme.primaryLight,
    borderWidth: 1.5,
    borderColor: theme.primary,
  },
  appliedText: { fontSize: 15, fontWeight: "700", color: theme.primaryDark },

  pendingBadge: {
    backgroundColor: theme.warning,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  pendingBadgeText: { fontSize: 11, fontWeight: "800", color: "#FFFFFF" },

  emptyApplicants: { alignItems: "center", paddingVertical: 24, gap: 8 },
  emptyApplicantsText: { color: theme.mutedText, fontSize: 14 },

  applicantCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 14,
    marginTop: 8,
    backgroundColor: theme.bg,
  },
  applicantHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 8,
  },
  applicantAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.primaryLight,
    alignItems: "center",
    justifyContent: "center",
  },
  applicantAvatarText: {
    fontSize: 12,
    fontWeight: "800",
    color: theme.primaryDark,
  },
  applicantName: { fontSize: 14, fontWeight: "800", color: theme.primaryText },
  coverLetterPreview: { fontSize: 12, color: theme.mutedText, marginTop: 2 },
  coverLetterFull: {
    fontSize: 13,
    color: theme.secondaryText,
    lineHeight: 19,
    fontStyle: "italic",
    marginBottom: 10,
    paddingTop: 6,
  },

  appStatusBadge: { paddingVertical: 4, paddingHorizontal: 8, borderRadius: 6 },
  appStatusText: { fontSize: 11, fontWeight: "700" },

  decisionRow: { flexDirection: "row", gap: 8 },
  rejectBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: theme.errorLight,
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  rejectBtnText: { fontWeight: "700", color: theme.error, fontSize: 13 },
  acceptBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: theme.primary,
  },
  acceptBtnText: { fontWeight: "700", color: "#FFFFFF", fontSize: 13 },
  chatBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: theme.primary,
    marginTop: 4,
  },
  chatBtnText: { fontWeight: "700", color: "#FFFFFF", fontSize: 13 },

  // ── Candidate profile inside applicant card ──────────────────────
  candidateNameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  candidateVerified: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 6,
    backgroundColor: theme.primaryLight,
  },
  candidateVerifiedText: {
    fontSize: 10,
    fontWeight: "700",
    color: theme.primaryDark,
  },
  candidateBio: {
    fontSize: 12,
    color: theme.mutedText,
    marginTop: 2,
    lineHeight: 16,
  },
  skillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginTop: 8 },
  skillChip: {
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: 8,
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.border,
  },
  skillChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: theme.secondaryText,
  },
  skillMore: { fontSize: 11, color: theme.mutedText, alignSelf: "center" },
  cvBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    alignSelf: "flex-start",
    marginTop: 8,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.primary,
    backgroundColor: theme.primaryLight,
  },
  cvBtnText: { fontSize: 12, fontWeight: "700", color: theme.primaryDark },
  coverLetterBox: {
    marginTop: 10,
    padding: 10,
    borderRadius: 10,
    backgroundColor: theme.surfaceAlt,
  },
  coverLetterLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: theme.mutedText,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 5,
  },

  stickyFooter: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surface,
  },
  applyBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 15,
    borderRadius: 16,
    backgroundColor: theme.primary,
  },
  applyBtnText: { fontSize: 17, fontWeight: "800", color: "#FFFFFF" },

  notFound: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  notFoundText: { fontSize: 16, fontWeight: "700", color: theme.secondaryText },
  backLink: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 10,
    backgroundColor: theme.primary,
  },
  backLinkText: { color: "#FFFFFF", fontWeight: "700" },

  // View counter chip
  viewChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: theme.surfaceAlt,
  },
  viewChipText: { fontSize: 12, color: theme.mutedText, fontWeight: "600" },

  // Verified badge on poster row
  posterVerified: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginTop: 2,
  },
  posterVerifiedText: { fontSize: 11, fontWeight: "700", color: "#0F766E" },

  // Report modal overlay handled via Alert; just need flag btn style
});
