import { StyleSheet } from "react-native";
import type { Colors } from "../../../src/theme/colors";

export function makeStyles(c: Colors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: c.bg },

    navbar: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 8,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
      gap: 4,
    },
    navBtn: { padding: 10, borderRadius: 10 },
    navRight: { flexDirection: "row", alignItems: "center" },
    navTitle: {
      flex: 1,
      fontSize: 15,
      fontWeight: "800",
      color: c.primaryText,
    },

    scroll: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 16 },

    heroCard: {
      backgroundColor: c.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: c.border,
      padding: 18,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },

    badgeRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginBottom: 12,
    },
    roleBadge: { paddingVertical: 4, paddingHorizontal: 10, borderRadius: 8 },
    roleBadgeText: { fontSize: 12, fontWeight: "700" },
    catBadge: {
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: c.surfaceAlt,
    },
    catBadgeText: { fontSize: 12, fontWeight: "600", color: c.secondaryText },
    statusBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 8,
    },
    statusDot: { width: 6, height: 6, borderRadius: 3 },
    statusText: { fontSize: 12, fontWeight: "700" },

    heroTitle: {
      fontSize: 24,
      fontWeight: "900",
      color: c.primaryText,
      lineHeight: 30,
      marginBottom: 8,
      letterSpacing: -0.3,
    },

    slotsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 14,
    },
    slotsText: {
      fontSize: 13,
      fontWeight: "700",
      color: c.primary,
    },

    metaRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 16,
    },
    metaChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingVertical: 6,
      paddingHorizontal: 11,
      borderRadius: 10,
      backgroundColor: c.surfaceAlt,
    },
    metaText: { fontSize: 13, color: c.secondaryText, fontWeight: "600" },
    wageChip: { backgroundColor: "#ECFDF5" },
    wageText: { color: "#065F46", fontWeight: "700" },

    posterRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingTop: 14,
      borderTopWidth: 1,
      borderColor: c.border,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: c.primaryLight,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarText: { fontSize: 14, fontWeight: "800", color: c.primaryDark },
    posterName: { fontSize: 14, fontWeight: "800", color: c.primaryText },
    posterLabel: { fontSize: 12, color: c.mutedText },

    section: {
      backgroundColor: c.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.border,
      padding: 16,
      marginBottom: 12,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "800",
      color: c.primaryText,
      flex: 1,
    },
    descText: { fontSize: 14, color: c.secondaryText, lineHeight: 22 },

    appliedBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      padding: 14,
      borderRadius: 14,
      marginBottom: 12,
      backgroundColor: c.primaryLight,
      borderWidth: 1.5,
      borderColor: c.primary,
    },
    appliedText: { fontSize: 15, fontWeight: "700", color: c.primaryDark },

    pendingBadge: {
      backgroundColor: c.warning,
      paddingVertical: 2,
      paddingHorizontal: 8,
      borderRadius: 6,
    },
    pendingBadgeText: { fontSize: 11, fontWeight: "800", color: "#FFFFFF" },

    filterRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginBottom: 8,
      marginTop: 4,
    },
    filterChip: {
      paddingVertical: 4,
      paddingHorizontal: 12,
      borderRadius: 20,
      backgroundColor: c.surfaceAlt,
      borderWidth: 1.5,
      borderColor: c.border,
    },
    filterChipActive: {
      backgroundColor: c.primaryLight,
      borderColor: c.primary,
    },
    filterChipText: { fontSize: 12, fontWeight: "600", color: c.mutedText },
    filterChipTextActive: { color: c.primaryDark, fontWeight: "700" },

    emptyApplicants: { alignItems: "center", paddingVertical: 24, gap: 8 },
    emptyApplicantsText: { color: c.mutedText, fontSize: 14 },

    applicantCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      padding: 14,
      marginTop: 8,
      backgroundColor: c.bg,
    },
    applicantHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      marginBottom: 8,
    },
    applicantAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: c.primaryLight,
      alignItems: "center",
      justifyContent: "center",
    },
    applicantAvatarText: {
      fontSize: 12,
      fontWeight: "800",
      color: c.primaryDark,
    },
    applicantName: { fontSize: 14, fontWeight: "800", color: c.primaryText },
    coverLetterPreview: { fontSize: 12, color: c.mutedText, marginTop: 2 },
    coverLetterFull: {
      fontSize: 13,
      color: c.secondaryText,
      lineHeight: 19,
      fontStyle: "italic",
      marginBottom: 10,
      paddingTop: 6,
    },

    appStatusBadge: {
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderRadius: 6,
    },
    appStatusText: { fontSize: 11, fontWeight: "700" },

    decisionRow: { flexDirection: "row", gap: 8 },
    decisionCol: { flexDirection: "column", gap: 6 },
    rejectBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      paddingVertical: 9,
      borderRadius: 10,
      backgroundColor: c.errorLight,
      borderWidth: 1,
      borderColor: "#FECACA",
    },
    rejectBtnText: { fontWeight: "700", color: c.error, fontSize: 13 },
    acceptBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      paddingVertical: 9,
      borderRadius: 10,
      backgroundColor: c.primary,
    },
    acceptBtnText: { fontWeight: "700", color: "#FFFFFF", fontSize: 13 },
    hireBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      paddingVertical: 9,
      borderRadius: 10,
      backgroundColor: c.success,
    },
    hireBtnText: { fontWeight: "700", color: "#FFFFFF", fontSize: 13 },
    chatBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 9,
      borderRadius: 10,
      backgroundColor: c.primary,
    },
    chatBtnText: { fontWeight: "700", color: "#FFFFFF", fontSize: 13 },

    // ── Candidate profile inside applicant card ──────────────────────
    candidateNameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    candidateVerified: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      paddingVertical: 2,
      paddingHorizontal: 6,
      borderRadius: 6,
      backgroundColor: c.primaryLight,
    },
    candidateVerifiedText: {
      fontSize: 10,
      fontWeight: "700",
      color: c.primaryDark,
    },
    candidateBio: {
      fontSize: 12,
      color: c.mutedText,
      marginTop: 2,
      lineHeight: 16,
    },
    skillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginTop: 8 },
    skillChip: {
      paddingVertical: 3,
      paddingHorizontal: 9,
      borderRadius: 8,
      backgroundColor: c.surfaceAlt,
      borderWidth: 1,
      borderColor: c.border,
    },
    skillChipText: {
      fontSize: 11,
      fontWeight: "700",
      color: c.secondaryText,
    },
    skillMore: { fontSize: 11, color: c.mutedText, alignSelf: "center" },
    cvBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      alignSelf: "flex-start",
      marginTop: 8,
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.primary,
      backgroundColor: c.primaryLight,
    },
    cvBtnText: { fontSize: 12, fontWeight: "700", color: c.primaryDark },
    coverLetterBox: {
      marginTop: 10,
      padding: 10,
      borderRadius: 10,
      backgroundColor: c.surfaceAlt,
    },
    coverLetterLabel: {
      fontSize: 10,
      fontWeight: "800",
      color: c.mutedText,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 5,
    },

    stickyFooter: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderTopWidth: 1,
      borderColor: c.border,
    },
    applyBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 15,
      borderRadius: 16,
      backgroundColor: c.primary,
    },
    applyBtnText: { fontSize: 17, fontWeight: "800", color: "#FFFFFF" },

    notFound: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
    },
    notFoundText: { fontSize: 16, fontWeight: "700", color: c.secondaryText },
    backLink: {
      paddingVertical: 8,
      paddingHorizontal: 20,
      borderRadius: 10,
      backgroundColor: c.primary,
    },
    backLinkText: { color: "#FFFFFF", fontWeight: "700" },

    // View counter chip
    viewChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: c.surfaceAlt,
    },
    viewChipText: { fontSize: 12, color: c.mutedText, fontWeight: "600" },

    // Verified badge on poster row
    posterVerified: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      marginTop: 2,
    },
    posterVerifiedText: { fontSize: 11, fontWeight: "700", color: "#0F766E" },

    // Report modal overlay handled via Alert; just need flag btn style

    // Similar jobs section
    similarSection: {
      marginTop: 4,
      marginBottom: 12,
    },
    similarScroll: {
      paddingHorizontal: 16,
      gap: 10,
    },
    similarCard: {
      width: 160,
      backgroundColor: c.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      padding: 12,
    },
    similarCardCategory: {
      fontSize: 10,
      fontWeight: "700",
      color: c.mutedText,
      textTransform: "uppercase",
      marginBottom: 4,
    },
    similarCardTitle: {
      fontSize: 13,
      fontWeight: "800",
      color: c.primaryText,
      lineHeight: 18,
      marginBottom: 6,
    },
    similarCardPoster: {
      fontSize: 11,
      color: c.secondaryText,
    },
  });
}
