import { StyleSheet } from "react-native";

export const theme = {
  primary: "#0D9488",
  primaryLight: "#CCFBF1",
  primaryDark: "#0F766E",
  accent: "#F97316",
  bg: "#F8FAFC",
  surface: "#FFFFFF",
  surfaceAlt: "#F1F5F9",
  primaryText: "#0F172A",
  secondaryText: "#64748B",
  mutedText: "#94A3B8",
  border: "#E2E8F0",
  success: "#10B981",
  successLight: "#D1FAE5",
  employer: "#7C3AED",
  employerLight: "#EDE9FE",
};

export const CATEGORY_COLORS: Record<string, { bg: string; text: string }> = {
  All: { bg: "#F1F5F9", text: "#64748B" },
  Hospitality: { bg: "#FFF7ED", text: "#C2410C" },
  Retail: { bg: "#EFF6FF", text: "#1D4ED8" },
  Tutoring: { bg: "#F5F3FF", text: "#6D28D9" },
  Events: { bg: "#FDF4FF", text: "#A21CAF" },
  Delivery: { bg: "#ECFDF5", text: "#065F46" },
  IT: { bg: "#F0F9FF", text: "#0369A1" },
  Office: { bg: "#FFFBEB", text: "#92400E" },
  Marketing: { bg: "#FFF1F2", text: "#BE123C" },
  Other: { bg: "#F8FAFC", text: "#475569" },
};

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: theme.bg },

  header: {
    backgroundColor: theme.surface,
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderColor: theme.border,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: theme.primaryText,
    letterSpacing: -0.3,
  },
  headerSub: {
    fontSize: 12,
    color: theme.mutedText,
    fontWeight: "500",
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.bg,
    borderWidth: 1.5,
    borderColor: theme.border,
    borderRadius: 14,
    paddingHorizontal: 12,
    height: 46,
    gap: 8,
  },
  searchInput: { flex: 1, color: theme.primaryText, fontSize: 15 },

  chipsRow: { paddingVertical: 10, paddingLeft: 16, gap: 7 },
  chip: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: theme.surface,
    borderWidth: 1.5,
    borderColor: theme.border,
    alignItems: "center",
    justifyContent: "center",
  },
  chipActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  chipText: {
    color: theme.secondaryText,
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  chipTextActive: {
    color: "#FFFFFF",
    fontWeight: "800",
  },

  list: { paddingHorizontal: 16, paddingTop: 4, paddingBottom: 32 },
  separator: { height: 12 },

  card: {
    backgroundColor: theme.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardPressed: { opacity: 0.92, transform: [{ scale: 0.99 }] },

  cardStrip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  cardStripText: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  stripRight: { flexDirection: "row", alignItems: "center", gap: 6 },
  roleBadge: { paddingVertical: 3, paddingHorizontal: 8, borderRadius: 6 },
  roleBadgeText: { fontSize: 11, fontWeight: "700" },
  expiryBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 5,
    backgroundColor: "#FEF3C7",
  },
  expiryBadgeText: { fontSize: 10, fontWeight: "700", color: "#92400E" },

  cardBody: { padding: 14, paddingTop: 10 },
  titleRow: { flexDirection: "row", alignItems: "flex-start", marginBottom: 5 },
  bookmarkBtn: { paddingLeft: 8, paddingTop: 2 },

  cardTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: theme.primaryText,
    lineHeight: 23,
  },
  cardDesc: {
    fontSize: 13,
    color: theme.secondaryText,
    lineHeight: 18,
    marginBottom: 10,
  },

  metaRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 12 },
  metaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: theme.surfaceAlt,
  },
  metaChipText: { fontSize: 12, color: theme.secondaryText, fontWeight: "600" },
  wageChip: { backgroundColor: "#ECFDF5" },
  wageChipText: { color: "#065F46", fontWeight: "700" },

  cardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 10,
    borderTopWidth: 1,
    borderColor: theme.border,
  },
  posterRow: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.primaryLight,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { fontSize: 12, fontWeight: "800", color: theme.primaryDark },
  posterName: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.primaryText,
    maxWidth: 120,
  },
  timeAgo: { fontSize: 11, color: theme.mutedText },

  applyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: theme.primary,
  },
  applyBtnText: { fontSize: 13, fontWeight: "800", color: "#FFFFFF" },

  // Recent searches
  recentRow: { marginTop: 8 },
  recentContent: { gap: 6, paddingRight: 4 },
  recentChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.border,
  },
  recentChipText: {
    fontSize: 12,
    color: theme.secondaryText,
    fontWeight: "600",
  },

  // Profile completeness banner
  banner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 16,
    marginTop: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: theme.primaryLight,
    borderWidth: 1,
    borderColor: theme.primary,
  },
  bannerText: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: theme.primaryDark,
  },
  bannerActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  bannerLink: { fontSize: 13, fontWeight: "800", color: theme.primary },
  bannerDismiss: { padding: 2 },

  // Chips ScrollView
  chipsScroll: { flexGrow: 0 },
  chipsRow: { paddingVertical: 10, paddingHorizontal: 16, gap: 8 },
  chip: {
    paddingVertical: 7,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: theme.surface,
    borderWidth: 1.5,
    borderColor: theme.border,
  },
  chipActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  chipText: {
    color: theme.secondaryText,
    fontSize: 13,
    fontWeight: "600",
  },
  chipTextActive: {
    color: "#FFFFFF",
    fontWeight: "800",
  },

  emptyWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 60,
    gap: 10,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: theme.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  emptyTitle: { fontSize: 18, fontWeight: "800", color: theme.primaryText },
  emptySubtitle: {
    fontSize: 14,
    color: theme.secondaryText,
    textAlign: "center",
  },
  refreshBtn: {
    marginTop: 6,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: theme.primary,
  },
  refreshBtnText: { fontWeight: "700", color: "#FFFFFF" },
});
