import { StyleSheet } from "react-native";
import type { Colors } from "../../src/theme/colors";

// CATEGORY_COLORS depends on dark/light mode
export function getCategoryColors(
  isDark: boolean,
): Record<string, { bg: string; text: string }> {
  if (!isDark) {
    return {
      All: { bg: "#F1F5F9", text: "#64748B" },
      Hospitality: { bg: "#FFF7ED", text: "#C2410C" },
      Retail: { bg: "#EFF6FF", text: "#1D4ED8" },
      Tutoring: { bg: "#F5F3FF", text: "#6D28D9" },
      Events: { bg: "#FDF4FF", text: "#A21CAF" },
      Delivery: { bg: "#ECFDF5", text: "#065F46" },
      IT: { bg: "#F0F9FF", text: "#0369A1" },
      Office: { bg: "#FFFBEB", text: "#92400E" },
      Marketing: { bg: "#FFF1F2", text: "#BE123C" },
      Other: { bg: "#F8FAFC", text: "#475569" },
    };
  }
  return {
    All: { bg: "#1E293B", text: "#94A3B8" },
    Hospitality: { bg: "#3B1A08", text: "#FB923C" },
    Retail: { bg: "#0D2145", text: "#60A5FA" },
    Tutoring: { bg: "#1F1346", text: "#C4B5FD" },
    Events: { bg: "#2D0A3E", text: "#E879F9" },
    Delivery: { bg: "#052E16", text: "#34D399" },
    IT: { bg: "#082035", text: "#38BDF8" },
    Office: { bg: "#2D1A04", text: "#FCD34D" },
    Marketing: { bg: "#3B0820", text: "#FB7185" },
    Other: { bg: "#1E293B", text: "#94A3B8" },
  };
}

export function makeStyles(c: Colors) {
  return StyleSheet.create({
    page: { flex: 1, backgroundColor: c.bg },

    // ── Compact header ──────────────────────────────────────────────
    header: {
      // backgroundColor: c.surface,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 6,
      borderBottomWidth: 1,
      borderColor: c.border,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 4,
    },
    searchBox: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.surfaceAlt,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 10,
      paddingHorizontal: 10,
      height: 38,
      gap: 6,
    },
    searchInput: { flex: 1, color: c.primaryText, fontSize: 14 },
    headerIconBtn: {
      width: 38,
      height: 38,
      borderRadius: 10,
      backgroundColor: c.surfaceAlt,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: "900",
      color: c.primaryText,
      letterSpacing: -0.3,
    },
    headerSub: { fontSize: 11, color: c.mutedText, fontWeight: "500" },

    list: { paddingHorizontal: 14, paddingTop: 6, paddingBottom: 32 },
    separator: { height: 10 },

    // ── Card ────────────────────────────────────────────────────────
    card: {
      backgroundColor: c.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.border,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: c.isDark ? 0.3 : 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    cardPressed: { opacity: 0.92, transform: [{ scale: 0.99 }] },

    // Left accent borders removed — keep type signal in role badge only
    cardEmployer: {},
    cardStudent: {},

    cardStrip: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderTopLeftRadius: 15,
      borderTopRightRadius: 15,
      backgroundColor: c.surfaceAlt,
    },
    cardStripText: {
      fontSize: 11,
      fontWeight: "700",
      color: c.secondaryText,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    stripRight: { flexDirection: "row", alignItems: "center", gap: 6 },
    roleBadge: {
      paddingVertical: 3,
      paddingHorizontal: 8,
      borderRadius: 6,
      backgroundColor: c.isDark ? "#2C2C2E" : "#E2E8F0",
    },
    roleBadgeText: { fontSize: 11, fontWeight: "700", color: c.secondaryText },
    expiryBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      paddingVertical: 2,
      paddingHorizontal: 6,
      borderRadius: 5,
      backgroundColor: c.warningLight,
    },
    expiryBadgeText: { fontSize: 10, fontWeight: "700", color: c.warning },
    urgentBadge: {
      paddingVertical: 2,
      paddingHorizontal: 7,
      borderRadius: 5,
      backgroundColor: "#FEE2E2",
    },
    urgentBadgeText: { fontSize: 10, fontWeight: "800", color: "#DC2626" },
    boostedBadge: {
      paddingVertical: 2,
      paddingHorizontal: 7,
      borderRadius: 5,
      backgroundColor: "#FEF3C7",
    },
    boostedBadgeText: { fontSize: 10, fontWeight: "800", color: "#D97706" },

    cardBody: { padding: 12, paddingTop: 8 },
    titleRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: 4,
    },
    bookmarkBtn: { paddingLeft: 8, paddingTop: 2 },

    cardTitle: {
      fontSize: 16,
      fontWeight: "800",
      color: c.primaryText,
      lineHeight: 22,
    },
    cardDesc: {
      fontSize: 13,
      color: c.secondaryText,
      lineHeight: 18,
      marginBottom: 8,
    },

    metaRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      marginBottom: 10,
    },
    metaChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingVertical: 3,
      paddingHorizontal: 7,
      borderRadius: 7,
      backgroundColor: c.surfaceAlt,
    },
    metaChipText: {
      fontSize: 11,
      color: c.secondaryText,
      fontWeight: "600",
    },
    wageChip: { backgroundColor: c.successLight },
    wageChipText: {
      color: c.isDark ? "#34D399" : "#065F46",
      fontWeight: "700",
    },

    cardFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingTop: 8,
      borderTopWidth: 1,
      borderColor: c.border,
    },
    posterRow: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
    avatar: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: c.primaryLight,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarText: { fontSize: 11, fontWeight: "800", color: c.primaryDark },
    posterName: {
      fontSize: 12,
      fontWeight: "700",
      color: c.primaryText,
      maxWidth: 120,
    },
    timeAgo: { fontSize: 10, color: c.mutedText },

    applyBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingVertical: 7,
      paddingHorizontal: 13,
      borderRadius: 10,
      backgroundColor: c.primary,
    },
    applyBtnText: { fontSize: 12, fontWeight: "800", color: "#FFFFFF" },

    footerRight: { flexDirection: "row", alignItems: "center", gap: 7 },

    interestedBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingVertical: 6,
      paddingHorizontal: 9,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: c.border,
      backgroundColor: c.surface,
    },
    interestedBtnActive: {
      backgroundColor: c.isDark ? "#3B0A0A" : "#FFF1F2",
      borderColor: c.isDark ? "#EF4444" : "#FCA5A5",
    },
    interestedCount: { fontSize: 11, fontWeight: "700", color: c.mutedText },
    interestedCountActive: { color: "#EF4444" },

    appliedBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingVertical: 6,
      paddingHorizontal: 11,
      borderRadius: 10,
      backgroundColor: c.primaryLight,
      borderWidth: 1.5,
      borderColor: c.primary,
    },
    appliedBadgeText: { fontSize: 11, fontWeight: "700", color: c.primary },

    saveSearchBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      alignSelf: "flex-start",
      marginHorizontal: 14,
      marginBottom: 4,
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: c.primaryLight,
      borderWidth: 1,
      borderColor: c.primary,
    },
    saveSearchText: { fontSize: 11, fontWeight: "700", color: c.primaryDark },

    recentRow: { marginTop: 6 },
    recentContent: { gap: 6, paddingRight: 4 },
    recentChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 20,
      backgroundColor: c.surfaceAlt,
      borderWidth: 1,
      borderColor: c.border,
    },
    recentChipText: {
      fontSize: 12,
      color: c.secondaryText,
      fontWeight: "600",
    },

    newJobsBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginHorizontal: 14,
      marginTop: 6,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: c.isDark ? "#451A03" : "#FFF7ED",
      borderWidth: 1,
      borderColor: c.isDark ? "#78350F" : "#FED7AA",
    },
    newJobsBannerText: {
      flex: 1,
      fontSize: 12,
      fontWeight: "700",
      color: c.isDark ? "#FED7AA" : "#92400E",
    },

    banner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginHorizontal: 14,
      marginTop: 6,
      padding: 10,
      borderRadius: 10,
      backgroundColor: c.primaryLight,
      borderWidth: 1,
      borderColor: c.primary,
    },
    bannerText: {
      flex: 1,
      fontSize: 12,
      fontWeight: "600",
      color: c.primaryDark,
    },
    bannerActions: { flexDirection: "row", alignItems: "center", gap: 8 },
    bannerLink: { fontSize: 12, fontWeight: "800", color: c.primary },
    bannerDismiss: { padding: 2 },

    chipsScroll: { flexShrink: 0 },
    chipsRow: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      gap: 6,
      flexDirection: "row",
    },
    chip: {
      paddingVertical: 5,
      paddingHorizontal: 14,
      borderRadius: 999,
      backgroundColor: c.surface,
      borderWidth: 1.5,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
    },
    chipActive: { backgroundColor: c.primary, borderColor: c.primary },
    chipText: { color: c.secondaryText, fontSize: 12, fontWeight: "600" },
    chipTextActive: { color: "#FFFFFF", fontWeight: "800" },

    modePill: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "center",
      gap: 5,
      marginBottom: 2,
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
    },
    modePillText: { fontSize: 11, fontWeight: "700" },
    modePillTextEmployer: { color: c.employer },
    modePillTextStudent: { color: c.primary },

    emptyWrap: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingTop: 60,
      gap: 10,
    },
    emptyIcon: {
      width: 68,
      height: 68,
      borderRadius: 22,
      backgroundColor: c.surfaceAlt,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 4,
    },
    emptyTitle: { fontSize: 17, fontWeight: "800", color: c.primaryText },
    emptySubtitle: {
      fontSize: 13,
      color: c.secondaryText,
      textAlign: "center",
    },
    refreshBtn: {
      marginTop: 6,
      paddingVertical: 9,
      paddingHorizontal: 18,
      borderRadius: 10,
      backgroundColor: c.primary,
    },
    refreshBtnText: { fontWeight: "700", color: "#FFFFFF" },
  });
}
