import { StyleSheet } from "react-native";

export const theme = {
  primary: "#0D9488",
  primaryLight: "#CCFBF1",
  primaryDark: "#0F766E",
  bg: "#F8FAFC",
  surface: "#FFFFFF",
  surfaceAlt: "#F1F5F9",
  primaryText: "#0F172A",
  secondaryText: "#64748B",
  mutedText: "#94A3B8",
  border: "#E2E8F0",
  success: "#10B981",
  successLight: "#D1FAE5",
  warning: "#F59E0B",
  warningLight: "#FEF3C7",
  error: "#EF4444",
  errorLight: "#FEE2E2",
};

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: theme.bg },

  header: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 4,
  },
  headerTitle: { fontSize: 24, fontWeight: "800", color: theme.primaryText },

  tabRow: {
    flexDirection: "row",
    marginHorizontal: 16,
    marginVertical: 10,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 12,
    padding: 3,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: "center",
  },
  tabBtnActive: { backgroundColor: theme.surface },
  tabBtnText: { fontSize: 14, fontWeight: "600", color: theme.mutedText },
  tabBtnTextActive: { color: theme.primaryText, fontWeight: "700" },

  list: { paddingHorizontal: 16, paddingTop: 4, paddingBottom: 24 },
  separator: { height: 10 },

  sectionDivider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginVertical: 14,
  },
  sectionLine: { flex: 1, height: 1, backgroundColor: theme.border },
  sectionLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.mutedText,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // Card
  card: {
    backgroundColor: theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  cardBody: { padding: 14 },
  cardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 6,
  },
  cardTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
    color: theme.primaryText,
    lineHeight: 21,
  },
  statusBadge: { paddingVertical: 3, paddingHorizontal: 8, borderRadius: 6 },
  statusText: { fontSize: 11, fontWeight: "700" },

  applicantName: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.secondaryText,
    marginBottom: 6,
  },

  coverLetter: {
    fontSize: 13,
    color: theme.secondaryText,
    lineHeight: 18,
    marginBottom: 8,
    fontStyle: "italic",
  },

  cardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
  },
  postedBy: { fontSize: 12, color: theme.mutedText },
  footerActions: { flexDirection: "row", gap: 8, alignItems: "center" },

  decisionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  acceptBtn: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: theme.primary,
    alignItems: "center",
  },
  acceptBtnText: { fontWeight: "700", color: "#FFFFFF", fontSize: 13 },
  rejectBtn: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: "center",
  },
  rejectBtnText: {
    fontWeight: "700",
    color: theme.secondaryText,
    fontSize: 13,
  },

  chatBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: theme.primary,
  },
  chatBtnText: { fontWeight: "700", color: "#FFFFFF", fontSize: 13 },

  rateBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: theme.warning,
    backgroundColor: theme.warningLight,
  },
  rateBtnText: { fontSize: 12, color: theme.warning, fontWeight: "700" },

  withdrawBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.border,
  },
  withdrawBtnText: { fontSize: 12, color: theme.mutedText, fontWeight: "600" },

  // ── Sent application box ─────────────────────────────────────────
  applicationBox: {
    backgroundColor: theme.surfaceAlt,
    borderRadius: 10,
    padding: 10,
    marginTop: 8,
    marginBottom: 4,
  },
  applicationLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: theme.mutedText,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 5,
  },
  applicationText: {
    fontSize: 13,
    color: theme.secondaryText,
    lineHeight: 19,
  },
  dateText: { fontSize: 11, color: theme.mutedText },
  seenText: { fontSize: 11, color: theme.success, fontWeight: "600" },
  disputeBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.error,
    backgroundColor: theme.errorLight,
  },
  disputeBtnText: { fontSize: 11, fontWeight: "700", color: theme.error },

  // ── Application timeline ─────────────────────────────────────────
  timeline: {
    marginTop: 12,
    marginBottom: 6,
    backgroundColor: theme.surfaceAlt,
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  timelineSectionLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: theme.mutedText,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  timelineDotsRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  timelineLabelsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  timelineStep: {
    alignItems: "center",
    gap: 4,
  },
  timelineDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: theme.border,
    backgroundColor: theme.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineConnector: {
    flex: 1,
    height: 2.5,
    backgroundColor: theme.border,
  },
  timelineLabel: {
    fontSize: 11,
    color: theme.mutedText,
    fontWeight: "600",
    textAlign: "center",
    flex: 1,
  },

  priceChip: {
    alignSelf: "flex-start",
    marginTop: 6,
    marginBottom: 2,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 6,
    backgroundColor: theme.primaryLight,
    borderWidth: 1,
    borderColor: theme.primary,
  },
  priceChipText: { fontSize: 11, fontWeight: "700", color: theme.primaryDark },

  // ── Candidate profile card (received tab) ────────────────────────
  candidateSection: {
    borderTopWidth: 1,
    borderTopColor: theme.border,
    paddingTop: 10,
    marginTop: 8,
    gap: 8,
  },
  candidateRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  candidateAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  candidateAvatarText: {
    fontSize: 14,
    fontWeight: "900",
    color: theme.primaryDark,
  },
  candidateNameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  candidateName: { fontSize: 15, fontWeight: "800", color: theme.primaryText },
  verifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 6,
    backgroundColor: theme.primaryLight,
  },
  verifiedText: { fontSize: 10, fontWeight: "700", color: theme.primaryDark },
  candidateBio: {
    fontSize: 12,
    color: theme.secondaryText,
    lineHeight: 17,
    marginTop: 2,
  },
  skillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 5 },
  skillChip: {
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: 8,
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.border,
  },
  skillChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: theme.secondaryText,
  },
  skillMore: { fontSize: 11, color: theme.mutedText, alignSelf: "center" },
  cvBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    alignSelf: "flex-start",
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.primary,
    backgroundColor: theme.primaryLight,
  },
  cvBtnText: { fontSize: 12, fontWeight: "700", color: theme.primaryDark },

  // Empty state
  emptyWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 80,
    gap: 10,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: theme.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  emptyTitle: { fontSize: 18, fontWeight: "800", color: theme.primaryText },
  emptySubtitle: {
    fontSize: 14,
    color: theme.secondaryText,
    textAlign: "center",
  },
});
