import { StyleSheet } from "react-native";
import type { Colors } from "../../src/theme/colors";

export function makeStyles(c: Colors) {
  return StyleSheet.create({
    page: { flex: 1, backgroundColor: c.bg },
    scroll: { paddingHorizontal: 16, paddingBottom: 40 },

    avatarSection: {
      alignItems: "center",
      paddingTop: 32,
      paddingBottom: 20,
      gap: 6,
    },
    avatar: {
      width: 80,
      height: 80,
      borderRadius: 28,
      backgroundColor: c.primaryLight,
      borderWidth: 2,
      borderColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 4,
    },
    avatarInitial: { fontSize: 34, fontWeight: "900", color: c.primary },
    name: { fontSize: 22, fontWeight: "900", color: c.primaryText },
    email: { fontSize: 13, color: c.mutedText },
    typeBadge: {
      marginTop: 4,
      paddingVertical: 4,
      paddingHorizontal: 12,
      borderRadius: 999,
    },
    typeBadgeText: { fontSize: 12, fontWeight: "700" },

    badgesRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flexWrap: "wrap",
      justifyContent: "center",
      marginTop: 4,
    },

    contactRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    contactLabel: { flexDirection: "row", alignItems: "center", gap: 6 },
    contactLabelText: {
      fontSize: 13,
      fontWeight: "600",
      color: c.secondaryText,
    },
    contactValue: { flex: 1, alignItems: "flex-end", paddingLeft: 12 },
    contactLinkText: {
      fontSize: 13,
      fontWeight: "600",
      color: c.primary,
      textAlign: "right",
    },
    contactEmpty: { fontSize: 12, color: c.mutedText, fontStyle: "italic" },

    statsRow: {
      flexDirection: "row",
      backgroundColor: c.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.border,
      paddingVertical: 16,
      marginBottom: 16,
    },
    statItem: { flex: 1, alignItems: "center" },
    statValue: { fontSize: 24, fontWeight: "900", color: c.primaryText },
    statLabel: {
      fontSize: 12,
      color: c.mutedText,
      fontWeight: "600",
      marginTop: 2,
    },
    statDivider: { width: 1, backgroundColor: c.border },

    section: {
      backgroundColor: c.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.border,
      padding: 14,
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: "800",
      color: c.mutedText,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 10,
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 10,
    },
    emptyHint: {
      fontSize: 13,
      color: c.mutedText,
      fontStyle: "italic",
      lineHeight: 18,
    },

    bioText: { fontSize: 14, color: c.secondaryText, lineHeight: 20 },

    infoRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 6,
    },
    infoText: { fontSize: 14, color: c.secondaryText },

    skillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
    skillChip: {
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: c.primaryLight,
      borderWidth: 1,
      borderColor: c.primary,
    },
    skillChipText: { fontSize: 12, fontWeight: "700", color: c.primary },

    settingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 6,
      marginBottom: 4,
    },
    settingLeft: { flexDirection: "row", alignItems: "center", gap: 8 },
    settingLabel: {
      fontSize: 14,
      color: c.primaryText,
      fontWeight: "600",
    },
    settingSubLabel: {
      fontSize: 11,
      color: c.mutedText,
      marginTop: 1,
      marginBottom: 10,
    },

    modeSection: { paddingVertical: 4 },
    modeHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 2,
    },
    modeTrack: {
      flexDirection: "row",
      backgroundColor: c.surfaceAlt,
      borderRadius: 12,
      padding: 3,
      gap: 2,
    },
    modeOption: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      paddingVertical: 9,
      borderRadius: 10,
    },
    modeOptionActive: {
      backgroundColor: c.surface,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: c.isDark ? 0.3 : 0.08,
      shadowRadius: 3,
      elevation: 2,
    },
    modeOptionEmployerActive: { backgroundColor: c.employerLight },
    modeOptionStudentActive: { backgroundColor: c.primaryLight },
    modeOptionText: { fontSize: 12, fontWeight: "600", color: c.mutedText },
    modeOptionTextActive: { fontWeight: "800", color: c.primaryText },
    modeOptionTextEmployer: { color: c.employer },
    modeOptionTextStudent: { color: c.primary },

    toggleRow: { flexDirection: "row", gap: 4 },
    langBtn: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surfaceAlt,
    },
    langBtnActive: {
      backgroundColor: c.primaryLight,
      borderColor: c.primary,
    },
    langBtnText: { fontSize: 12, fontWeight: "700", color: c.mutedText },
    langBtnTextActive: { color: c.primary },

    verifyBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      marginTop: 6,
      paddingVertical: 5,
      paddingHorizontal: 12,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: c.employer,
      alignSelf: "center",
    },
    verifyBtnText: { fontSize: 12, fontWeight: "700", color: c.employer },

    workHistorySection: { marginBottom: 16 },
    workHistorySectionTitle: {
      fontSize: 13,
      fontWeight: "800",
      color: c.secondaryText,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 8,
    },
    workHistoryItem: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    workHistoryTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: c.primaryText,
    },
    workHistoryMeta: { fontSize: 12, color: c.mutedText, marginTop: 2 },

    signOutBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
      marginTop: 4,
    },
    signOutText: { fontSize: 15, fontWeight: "700", color: c.error },

    editBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      marginTop: 8,
      paddingVertical: 6,
      paddingHorizontal: 14,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: c.primary,
      backgroundColor: c.primaryLight,
    },
    editBtnText: { fontSize: 13, fontWeight: "700", color: c.primary },

    fieldLabel: {
      fontSize: 12,
      fontWeight: "700",
      color: c.mutedText,
      textTransform: "uppercase",
      letterSpacing: 0.4,
      marginBottom: 6,
      marginTop: 12,
    },
    fieldInput: {
      backgroundColor: c.surfaceAlt,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 14,
      color: c.primaryText,
    },
    fieldTextarea: { minHeight: 80, textAlignVertical: "top" as const },
    fieldHint: { fontSize: 11, color: c.mutedText, marginTop: 4 },

    editActions: {
      flexDirection: "row",
      gap: 10,
      marginTop: 20,
    },
    cancelBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
    },
    cancelBtnText: {
      fontSize: 14,
      fontWeight: "700",
      color: c.secondaryText,
    },
    saveBtn: {
      flex: 2,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: c.primary,
      alignItems: "center",
    },
    saveBtnText: { fontSize: 14, fontWeight: "800", color: "#FFFFFF" },

    verifiedBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      marginTop: 6,
      paddingVertical: 3,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: c.primaryLight,
      borderWidth: 1,
      borderColor: c.primary,
    },
    verifiedText: { fontSize: 11, fontWeight: "700", color: c.primaryDark },

    ratingRow: { flexDirection: "row", alignItems: "center", gap: 3 },

    cvLinkRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 8,
      paddingHorizontal: 10,
      backgroundColor: c.primaryLight,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.primary,
    },
    cvLinkText: { flex: 1, fontSize: 13, color: c.primary, fontWeight: "600" },
  });
}
