import { StyleSheet } from "react-native";

export const theme = {
  primary: "#0D9488",
  primaryLight: "#CCFBF1",
  bg: "#F8FAFC",
  surface: "#FFFFFF",
  surfaceAlt: "#F1F5F9",
  primaryText: "#0F172A",
  secondaryText: "#64748B",
  mutedText: "#94A3B8",
  border: "#E2E8F0",
  error: "#EF4444",
  employer: "#7C3AED",
  employerLight: "#EDE9FE",
};

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: theme.bg },
  scroll: { paddingHorizontal: 16, paddingBottom: 40 },

  avatarSection: {
    alignItems: "center",
    paddingTop: 32,
    paddingBottom: 20,
    gap: 6,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 28,
    backgroundColor: theme.primaryLight,
    borderWidth: 2,
    borderColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  avatarInitial: { fontSize: 34, fontWeight: "900", color: theme.primary },
  name: { fontSize: 22, fontWeight: "900", color: theme.primaryText },
  email: { fontSize: 13, color: theme.mutedText },
  typeBadge: {
    marginTop: 4,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  typeBadgeText: { fontSize: 12, fontWeight: "700" },

  statsRow: {
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    paddingVertical: 16,
    marginBottom: 16,
  },
  statItem: { flex: 1, alignItems: "center" },
  statValue: { fontSize: 24, fontWeight: "900", color: theme.primaryText },
  statLabel: {
    fontSize: 12,
    color: theme.mutedText,
    fontWeight: "600",
    marginTop: 2,
  },
  statDivider: { width: 1, backgroundColor: theme.border },

  section: {
    backgroundColor: theme.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 14,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: theme.mutedText,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
  },

  bioText: { fontSize: 14, color: theme.secondaryText, lineHeight: 20 },

  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  infoText: { fontSize: 14, color: theme.secondaryText },

  skillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  skillChip: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: theme.primaryLight,
    borderWidth: 1,
    borderColor: theme.primary,
  },
  skillChipText: { fontSize: 12, fontWeight: "700", color: theme.primary },

  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
    marginBottom: 4,
  },
  settingLeft: { flexDirection: "row", alignItems: "center", gap: 8 },
  settingLabel: { fontSize: 14, color: theme.primaryText, fontWeight: "600" },

  toggleRow: { flexDirection: "row", gap: 4 },
  langBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.surfaceAlt,
  },
  langBtnActive: {
    backgroundColor: theme.primaryLight,
    borderColor: theme.primary,
  },
  langBtnText: { fontSize: 12, fontWeight: "700", color: theme.mutedText },
  langBtnTextActive: { color: theme.primary },

  // ── Verify identity ─────────────────────────────────────────────
  verifyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 6,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#7C3AED",
    alignSelf: "center",
  },
  verifyBtnText: { fontSize: 12, fontWeight: "700", color: "#7C3AED" },

  // ── Work history ─────────────────────────────────────────────────
  workHistorySection: { marginBottom: 16 },
  workHistorySectionTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: theme.secondaryText,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  workHistoryItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  workHistoryTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.primaryText,
  },
  workHistoryMeta: { fontSize: 12, color: theme.mutedText, marginTop: 2 },

  signOutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
    marginTop: 4,
  },
  signOutText: { fontSize: 15, fontWeight: "700", color: theme.error },

  editBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: theme.primary,
    backgroundColor: theme.primaryLight,
  },
  editBtnText: { fontSize: 13, fontWeight: "700", color: theme.primary },

  fieldLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.mutedText,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 6,
    marginTop: 12,
  },
  fieldInput: {
    backgroundColor: theme.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: theme.primaryText,
  },
  fieldTextarea: { minHeight: 80, textAlignVertical: "top" },
  fieldHint: { fontSize: 11, color: theme.mutedText, marginTop: 4 },

  editActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 20,
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: "center",
  },
  cancelBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.secondaryText,
  },
  saveBtn: {
    flex: 2,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: theme.primary,
    alignItems: "center",
  },
  saveBtnText: { fontSize: 14, fontWeight: "800", color: "#FFFFFF" },

  // Verified badge
  verifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 6,
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "#CCFBF1",
    borderWidth: 1,
    borderColor: "#0D9488",
  },
  verifiedText: { fontSize: 11, fontWeight: "700", color: "#0F766E" },

  // Rating row in stats
  ratingRow: { flexDirection: "row", alignItems: "center", gap: 3 },

  // CV link
  cvLinkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: "#F0FDF9",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#0D9488",
  },
  cvLinkText: { flex: 1, fontSize: 13, color: "#0D9488", fontWeight: "600" },
});
